- name: check need copy fles
  raw: stat /opt/docker/VERSION-{{ DOCKER_VERSION }}.md
  register: need_copy_files
  ignore_errors: True

- name: mkdir -p /opt/docker /etc/docker
  raw: mkdir -p /opt/docker /etc/docker

- name: copy files to /opt/docker
  copy:
    src: ./
    dest: /opt/docker
  when: need_copy_files is failed

- name: template install.sh
  template: src=install.sh dest=/opt/docker/install.sh mode=0755

- name: template uninstall.sh
  template: src=uninstall.sh dest=/opt/docker/uninstall.sh mode=0755

- name: /opt/docker/install.sh
  raw: /opt/docker/install.sh
  when: need_copy_files is failed
