- name: check need copy files
  raw: stat /opt/docker/{{ DOCKER_VERSION }}/bin/docker
  register: need_copy_files
  ignore_errors: True

- name: mkdir -p /opt/docker /etc/docker
  raw: mkdir -p /opt/docker /etc/docker

- name: copy files to /opt/docker
  copy:
    src: ./
    dest: /opt/docker
  when: need_copy_files is failed

- name: /opt/docker/ansible-docker.sh
  raw: bash /opt/docker/ansible-docker.sh
  when: need_copy_files is failed
