# install kernel
- name: install kernel
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
  script: "{{ lookup('first_found', findme)}}"
  vars:
    findme:
      - install-kernel-{{ ansible_distribution }}.sh
      - install.sh
  when: 
  - ansible_kernel is version('5.4','<')