- name: mkdir -p /etc/kubernetes/services/k8s-registry
  raw: mkdir -p /etc/kubernetes/services/k8s-registry

- name: check regsitry version
  raw: stat /etc/kubernetes/services/k8s-registry/.beagle_registry_version_{{ BEAGLE_REGISTRY_VERSION }}
  register: need_change_version
  ignore_errors: True

- name: check need copy images
  raw: stat {{ K8S_DATA_PATH }}/registry/docker/registry/v2/repositories
  register: need_copy_images
  ignore_errors: True

- name: mkdir -p /tmp/registry/images
  raw: mkdir -p /tmp/registry/images
  when: 
    - REGISTRY_LOCAL == "registry.beagle.default:6444/k8s" 
    - need_copy_images is failed or need_change_version is failed

- name: copy files to /tmp/registry/images
  copy:
    src: ./images
    dest: /tmp/registry
  when: 
    - REGISTRY_LOCAL == "registry.beagle.default:6444/k8s" 
    - need_copy_images is failed or need_change_version is failed

- name: check need copy bin
  raw: stat /opt/bin/registry
  register: need_copy_bin
  ignore_errors: True

- name: mkdir -p /tmp/registry/bin
  raw: mkdir -p /tmp/registry/bin
  when: need_copy_bin is failed

- name: copy files to /tmp/registry/bin
  copy:
    src: ./bin
    dest: /tmp/registry
  when: 
    - need_copy_bin is failed or need_change_version is failed

- name: template registry.beagle.default.cnf
  template: src=config/registry.beagle.default.cnf dest=/etc/kubernetes/services/k8s-registry/registry.beagle.default.cnf

- name: template config/config.yml
  template: src=config/config.yml dest=/etc/kubernetes/services/k8s-registry/config.yml

- name: template config/auth
  template: src=config/auth dest=/etc/kubernetes/services/k8s-registry/auth

- name: template services/k8s-registry-auth.service
  template: src=services/registryauth.service dest=/etc/systemd/system/k8s-registry.service

- name: template registry.sh
  template: src=scripts/registry.sh dest=/etc/kubernetes/scripts/registry.sh mode=0755

- name: /etc/kubernetes/scripts/registry.sh
  raw: /etc/kubernetes/scripts/registry.sh
