- name: mkdir -p /etc/kubernetes/services/k8s-registry
  raw: mkdir -p /etc/kubernetes/services/k8s-registry /etc/kubernetes/scripts /etc/kubernetes/ansible /etc/kubernetes/downloads

- name: check need copy images
  raw: stat /etc/kubernetes/ansible/ansible-kubernetes-images-{{ K8S_VERSION }}-{{ K8S_ARCH }}.tgz
  register: need_copy_images
  ignore_errors: True

- name: copy files to /etc/kubernetes/ansible
  copy:
    src: ./images/
    dest: /etc/kubernetes/ansible
  when:
    - REGISTRY_LOCAL == "registry.beagle.default:6444/k8s"
    - need_copy_images is failed

- name: check need copy bin
  raw: stat /etc/kubernetes/downloads/registry-{{ BEAGLE_REGISTRY_VERSION }}
  register: need_copy_bin
  ignore_errors: True

- name: copy files to /etc/kubernetes/downloads
  copy:
    src: ./bin/
    dest: /etc/kubernetes/downloads
  when:
    - need_copy_bin is failed

- name: template registry.beagle.default.cnf
  template: src=config/registry.beagle.default.cnf dest=/etc/kubernetes/services/k8s-registry/registry.beagle.default.cnf

- name: template config/config.yml
  template: src=config/config.yml dest=/etc/kubernetes/services/k8s-registry/config.yml

- name: template config/auth
  template: src=config/auth dest=/etc/kubernetes/services/k8s-registry/auth

- name: template services/k8s-registry-auth.service
  template: src=services/registryauth.service dest=/etc/systemd/system/k8s-registry.service

- name: template registry.sh
  template: src=scripts/registry.sh dest=/etc/kubernetes/scripts/registry.sh mode=0755

- name: /etc/kubernetes/scripts/registry.sh
  raw: /etc/kubernetes/scripts/registry.sh
