apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
    app.bd-apaas.com/cluster-component: core
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  containers:
  - name: kube-scheduler
    image: {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['KUBE-SCHEDULER']['NAME'] }}:{{ K8S_IMAGES['KUBE-SCHEDULER']['VERSION'] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}
    command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/config/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/config/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/config/scheduler.conf
    - --leader-elect=true
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/config
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/config
      type: DirectoryOrCreate
    name: kubeconfig
