static_resources:
  listeners:
    - name: https-kubernetes
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 6443
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: destination
                cluster: kubernetes
    - name: https-registry
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 6444
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: destination
                cluster: registry
  clusters:
    - name: kubernetes
      connect_timeout: 30s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: kubernetes
        endpoints:
          - lb_endpoints:
{% for host in groups['master'] %}
              - endpoint:
                  health_check_config:
                    port_value: 6443
                  address:
                    socket_address:
                      address: {{ hostvars[host]['ansible_facts'][IFACE]['ipv4']['address'] }}
                      port_value: 6443
{% endfor %}
    - name: registry
      connect_timeout: 30s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: registry
        endpoints:
          - lb_endpoints:
{% for host in groups['master'] %}
              - endpoint:
                  health_check_config:
                    port_value: 6444
                  address:
                    socket_address:
                      address: {{ hostvars[host]['ansible_facts'][IFACE]['ipv4']['address'] }}
                      port_value: 6444
{% endfor %}
