---
# install sys
- name: sys.sh
  environment:
    AUTHORIZED_KEYS: '{% for ssh_key in SSH_INSTALL_KEYS %}{{ SSH_KEYS[ssh_key] }}{% if loop.last %}{% else %},{% endif %}{% endfor %}'
  script: sys.sh

- name: CentOS SELINUX set
  when: "ansible_distribution == 'CentOS'"
  script: centos.sh

- name: RedHat SELINUX set
  when: "ansible_distribution == 'RedHat'"
  script: centos.sh