- name: check need copy fles
  raw: stat /opt/bin/gateway
  register: need_copy_files
  ignore_errors: True

- name: mkdir -p /tmp/gateway
  raw: mkdir -p /tmp/gateway
  when: need_copy_files is failed

- name: copy files to /tmp/gateway
  copy:
    src: ./
    dest: /tmp/gateway
  when: need_copy_files is failed

- name: template gateway.sh
  template: src=scripts/gateway.sh dest=/etc/kubernetes/scripts/gateway.sh mode=0755

- name: /etc/kubernetes/scripts/gateway.sh
  raw: /etc/kubernetes/scripts/gateway.sh

- name: template config/global.yaml
  template: src=config/global.yaml dest=/etc/kubernetes/services/k8s-gateway/global.yaml

- name: template config/router.yaml
  template: src=config/router.yaml dest=/etc/kubernetes/services/k8s-gateway/router.yaml

- name: check need services/k8s-gateway.service
  raw: stat /etc/systemd/system/k8s-gateway.service
  register: need_services_gateway
  ignore_errors: True

- name: template services/k8s-gateway.service
  template: src=services/gateway.service dest=/etc/systemd/system/k8s-gateway.service

- name: start services k8s-gateway.service
  raw: systemctl daemon-reload && systemctl enable k8s-gateway.service && systemctl start k8s-gateway.service
  when: need_services_gateway is failed
