tcp:
  routers:
    k8s:
      entryPoints:
        - https-k8s
      rule: "HostSNI(`kubernetes.beagle.default`)"
      service: kubernetes
      tls:
        passthrough: true
    registry:
      entryPoints:
        - https-registry
      rule: "HostSNI(`registry.beagle.default`)"
      service: registry
      tls:
        passthrough: true
  services:
    kubernetes:
      loadBalancer:
        servers:
{% for host in groups['master'] %}
          - address: "{{ hostvars[host]['ansible_facts'][IFACE]['ipv4']['address'] }}:6443"
{% endfor %}
    registry:
      loadBalancer:
        servers:
{% for host in groups['master'] %}
          - address: "{{ hostvars[host]['ansible_facts'][IFACE]['ipv4']['address'] }}:6444"
{% endfor %}