
- name: mkdir -p /etc/kubernetes/ansible
  raw: mkdir -p /etc/kubernetes/ansible

- name: docker pull pause
  raw: /opt/bin/docker pull {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['PAUSE']['NAME'] }}:{{ K8S_IMAGES['PAUSE']['VERSION'] }}{{ '-%s' | format(K8S_ARCH) | replace('-amd64', '') }}
