- name: mkdir -p /etc/kubernetes/scripts
  raw: mkdir -p /etc/kubernetes/scripts

- name: template envoy.sh
  template: src=scripts/envoy.sh dest=/etc/kubernetes/scripts/envoy.sh mode=0755

- name: /etc/kubernetes/scripts/envoy.sh
  raw: /etc/kubernetes/scripts/envoy.sh
