- name: mkdir -p /etc/kubernetes/addons/kube-system
  raw: mkdir -p /etc/kubernetes/addons/kube-system

- name: check need kube-proxy.yaml
  raw: stat /etc/kubernetes/addons/kube-system/kube-proxy.yaml
  register: need_addons_proxy
  ignore_errors: True

- name: template kube-proxy.yaml
  template: src=kube-proxy.yaml dest=/etc/kubernetes/addons/kube-system/kube-proxy.yaml

- name: kubectl create -f kube-proxy.yaml
  raw: /opt/bin/kubectl create -f /etc/kubernetes/addons/kube-system/kube-proxy.yaml
  when: 
  - need_addons_proxy is failed

- name: check need flannel.yaml
  raw: stat /etc/kubernetes/addons/kube-system/flannel.yaml
  register: need_addons_flannel
  ignore_errors: True

- name: template flannel.yaml
  template: src=flannel.yaml dest=/etc/kubernetes/addons/kube-system/flannel.yaml

- name: kubectl create -f flannel.yaml
  raw: /opt/bin/kubectl create -f /etc/kubernetes/addons/kube-system/flannel.yaml
  when: 
  - need_addons_flannel is failed  