
- name: mkdir -p /etc/kubernetes/ansible
  raw: mkdir -p /etc/kubernetes/ansible

- name: check need /etc/kubernetes/ansible/.ansible-kubelet-images
  raw: stat /etc/kubernetes/ansible/.ansible-kubelet-images
  register: need_kubelet_images
  ignore_errors: True

- name: docker pull kube-apiserver
  raw: /opt/bin/docker pull {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['KUBE-APISERVER']['NAME'] }}:{{ K8S_IMAGES['KUBE-APISERVER']['VERSION'] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}
  when:
    - need_kubelet_images is failed

- name: docker pull kube-controller-manager
  raw: /opt/bin/docker pull {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['KUBE-CONTROLLER-MANAGER']['NAME'] }}:{{ K8S_IMAGES['KUBE-CONTROLLER-MANAGER']['VERSION'] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}
  when:
    - need_kubelet_images is failed

- name: docker pull kube-scheduler
  raw: /opt/bin/docker pull {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['KUBE-SCHEDULER']['NAME'] }}:{{ K8S_IMAGES['KUBE-SCHEDULER']['VERSION'] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}
  when:
    - need_kubelet_images is failed

- name: docker pull etcd
  raw: /opt/bin/docker pull {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['ETCD']['NAME'] }}:{{ K8S_IMAGES['ETCD']['VERSION'] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}
  when:
    - need_kubelet_images is failed

- name: docker pull pause
  raw: /opt/bin/docker pull {{ REGISTRY_LOCAL }}/{{ K8S_IMAGES['PAUSE']['NAME'] }}:{{ K8S_IMAGES['PAUSE']['VERSION'] }}{{ '-%s' | format(K8S_ARCH) | replace('-amd64', '') }}
  when:
    - need_kubelet_images is failed

- name: touch /etc/kubernetes/ansible/.ansible-kubelet-images
  raw: touch /etc/kubernetes/ansible/.ansible-kubelet-images
  when:
    - need_kubelet_images is failed
