- block:
    - name: mkdir -p /etc/kubernetes/addons/kube-system
      raw: mkdir -p /etc/kubernetes/addons/kube-system

    - name: check need kube-proxy.yaml
      raw: stat /etc/kubernetes/addons/kube-system/kube-proxy.yaml
      register: need_addons_proxy
      ignore_errors: True

    - name: template kube-proxy.yaml
      template: src=kube-proxy.yaml dest=/etc/kubernetes/addons/kube-system/kube-proxy.yaml

    - name: kubectl create -f kube-proxy.yaml
      raw: /opt/bin/kubectl create -f /etc/kubernetes/addons/kube-system/kube-proxy.yaml
      when:
        - need_addons_proxy is failed
  when:
    - ansible_kernel is version('4.19.57','<')

- name: mkdir -p /etc/kubernetes/charts
  raw: mkdir -p /etc/kubernetes/charts

- name: check need cilium files
  raw: stat /etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.md
  register: need_addons_cilium_files
  ignore_errors: True

- name: copy files to /etc/kubernetes/charts
  copy:
    src: ./
    dest: /etc/kubernetes/charts
  when:
    - need_addons_cilium_files is failed

- name: template beagle-cilium.yaml
  template: src=beagle-cilium.yaml dest=/etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.yaml
  when:
    - need_addons_cilium_files is failed
    - ansible_kernel is version('4.19.57','>=')

- name: template beagle-cilium.yaml
  template: src=beagle-cilium-proxy.yaml dest=/etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.yaml
  when:
    - need_addons_cilium_files is failed
    - ansible_kernel is version('4.19.57','<')

- name: template beagle-cilium.md
  template: src=beagle-cilium.md dest=/etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.md
  when:
    - need_addons_cilium_files is failed

- name: check need cilium install
  raw: helm list --namespace kube-system | grep cilium
  register: need_addons_cilium_install
  ignore_errors: True

- name: helm install cilium
  raw: /opt/bin/helm install cilium /etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.tgz --namespace kube-system -f /etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.yaml
  when:
    - need_addons_cilium_install is failed

- name: helm upgrade cilium
  raw: /opt/bin/helm upgrade cilium /etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.tgz --namespace kube-system -f /etc/kubernetes/charts/beagle-cilium-{{ BEAGLE_CILIUM_VERSION }}.yaml
  when:
    - need_addons_cilium_install
