- name: mkdir -p /etc/kubernetes/addons/kube-system
  raw: mkdir -p /etc/kubernetes/addons/kube-system

- name: check need cilium-hubble.ingress.yaml
  raw: stat /etc/kubernetes/addons/kube-system/cilium-hubble.ingress.yaml
  register: need_addons_ingress
  ignore_errors: True

- name: template cilium-hubble.ingress.yaml
  template: src=cilium-hubble.ingress.yaml dest=/etc/kubernetes/addons/kube-system/cilium-hubble.ingress.yaml

- name: kubectl create -f cilium-hubble.ingress.yaml
  raw: /opt/bin/kubectl create -f /etc/kubernetes/addons/kube-system/cilium-hubble.ingress.yaml
  when: 
  - need_addons_ingress is failed