- name: template kubelet.cnf
  template: src=kubelet.cnf dest=/etc/kubernetes/ssl/kubelet.cnf

- name: template kubelet.sh
  template: src=kubelet.sh dest=/etc/kubernetes/ssl/kubelet.sh mode=0755

- name: Run kubelet.sh
  raw: /etc/kubernetes/ssl/kubelet.sh