- name: check need sys-fs-bpf.mount
  raw: stat /etc/systemd/system/sys-fs-bpf.mount
  register: need_bpf_mount
  ignore_errors: True

- name: template sys-fs-bpf.mount
  template: src=services/sys-fs-bpf.mount dest=/etc/systemd/system/sys-fs-bpf.mount mode=0755
  when: 
    - need_bpf_mount is failed 

- name: systemctl daemon-reload
  raw: systemctl daemon-reload
  when: 
    - need_bpf_mount is failed 

- name: systemctl enable sys-fs-bpf.mount
  raw: systemctl enable sys-fs-bpf.mount
  when: 
    - need_bpf_mount is failed 

- name: systemctl start sys-fs-bpf.mount
  raw: systemctl start sys-fs-bpf.mount
  when: 
    - need_bpf_mount is failed 