---
# iface
IFACE: "{{ ansible_facts['default_ipv4']['interface'] }}"

# host define
HOST_IP: "{{ ansible_facts[IFACE]['ipv4']['address'] }}"

## HTTP_SERVER , HTTP服务器
## 调试安装过程种使用的文件下载服务器，二进制安装包存储在这里
HTTP_SERVER: 'https://cache.wodcloud.com/kubernetes/k8s'

## REGISTRY_LOCAL , Docker镜像服务器
## 安装过程种使用的容器镜像服务器
REGISTRY_LOCAL: 'registry.beagle.default:6444/k8s'

# docker options
## DOCKER_DATA_PATH ， docker将数据存储至此目录，转移后docker将数据存储至额外的硬盘，避免系统盘被占满
# DOCKER_DATA_PATH: "/data/kubernetes/docker"
## DOCKER_VERSION , docker的安装版本
DOCKER_VERSION: '20.10.18'

## K8S_ARCH, 服务器的CPU架构
## 可选值：amd64，arm64，ppc64le，mips64le
K8S_ARCH: 'amd64'

# 镜像
K8S_IMAGES:
  KUBELET:
    NAME: kubelet
    VERSION: 'v1.24.7-beagle'
  KUBE-APISERVER:
    NAME: kube-apiserver
    VERSION: 'v1.24.7-beagle'
  KUBE-CONTROLLER-MANAGER:
    NAME: kube-controller-manager
    VERSION: 'v1.24.7-beagle'
  KUBE-SCHEDULER:
    NAME: kube-scheduler
    VERSION: 'v1.24.7-beagle'
  KUBE-PROXY:
    NAME: kube-proxy
    VERSION: 'v1.24.7-beagle'
  KUBECTL:
    NAME: kubectl
    VERSION: 'v1.24.7-beagle'
  PAUSE:
    NAME: pause
    VERSION: '3.7'
  KUBE-CNI-PLUGINS:
    NAME: kube-cni-plugins
    VERSION: 'v1.1.1'
  ETCD:
    NAME: etcd
    VERSION: 'v3.5.5'
  ETCDCTL:
    NAME: etcdctl
    VERSION: 'v3.5.5'
  FLANNEL:
    NAME: flannel
    VERSION: 'v0.19.2'
  CILIUM:
    NAME: cilium
    VERSION: '1.11.9'
  CILIUM-OPERATOR:
    NAME: cilium-operator-generic
    VERSION: '1.11.9'
  CILIUM-HUBBLE-RELAY:
    NAME: cilium-hubble-relay
    VERSION: '1.11.9'
  CILIUM-HUBBLE-UI:
    NAME: cilium-hubble-ui
    VERSION: '0.9.2'
  CILIUM-HUBBLE-UI-BACKEND:
    NAME: cilium-hubble-ui-backend
    VERSION: '0.9.2'
  COREDNS:
    NAME: coredns
    VERSION: 'v1.9.4'
  HELM:
    NAME: helm
    VERSION: 'v3.10.0'
  BUSYBOX:
    NAME: busybox
    VERSION: '1.34'
  NERDCTL:
    NAME: nerdctl
    VERSION: 'v0.23.0'
  DEVOPS_DOCKER_IMAGES:
    NAME: devops-docker-images
    VERSION: '1.0'

#### k8s 可选设置 ####
# K8S_ADMIN_TOKEN , 设置集群的管理员静态Token
K8S_ADMIN_TOKEN: pleasechangeit

# K8S_NETWORK_PLUGIN , 网络插件cilium, flannel
K8S_NETWORK_PLUGIN: cilium

# K8S_UPSTREAM_DNSIP , 设置集群的外部DNS
# K8S_UPSTREAM_DNSIP: 114.114.114.114

#### k8s 高级设置 ####
# K8S_POD_NETWORK , 集群设置，容器网络CIDR设置
# K8S_POD_NETWORK ， 10.0.0.0/11 = 8096个节点，推荐不超过5000个节点，500
K8S_POD_NETWORK: 10.2.0.0/16
# K8S_SERVICE_IP_RANGE ， 集群设置，Service网络CIDR设置
# K8S_SERVICE_IP_RANGE ， 不能小于12，如果小于12，ServiceIP池过大，apiserver不启动
K8S_SERVICE_IP_RANGE: 10.3.0.0/16
# K8S_SERVICE_IP_RANGE ， 集群设置，Service网络允许开放的NodePort端口
K8S_SERVICE_PORT_RANGE: 1-65535
# K8S_NODE_PODCIDRMASK，节点设置，节点子网掩码，默认值为24，
# 子网掩码为21时，以K8S_POD_NETWORK掩码为16计算，集群规模为32节点，每节点可分配2000个pod
# 子网掩码为22时，集群规模为64节点，每节点可分配1000个pod
# 子网掩码为23时，集群规模为128节点，每节点可分配500个pod
# 子网掩码为24时，集群规模为256节点，每节点可分配250个pod
K8S_NODE_PODCIDRMASK: 24
# K8S_NODE_MAXPODS，节点设置，最大运行Pods数量限制，默认值110，
# 不能超过K8S_NODE_PODCIDRMASK子网掩码计算的最大Pod数量
K8S_NODE_MAXPODS: 110
