- hosts: all
  gather_facts: False
  roles:
    - wod.python

- hosts: all
  roles:
    - wod.sys
    - wod.k8s-ssl
    - wod.bpf-mount
    - wod.docker

- hosts: master
  roles:
    - role: wod.k8s-ssl-master
    - role: wod.k8s-ssl-kubelet
    - role: wod.k8s-ssl-etcd
    - role: wod.registry
    - role: wod.docker-login
    - role: wod.k8s-cni
    - role: wod.k8s-etcd
    - role: wod.k8s-master
    - role: wod.k8s-kubelet
    - role: wod.k8s-kubectl
    - role: wod.nerdctl
    - role: wod.k8s-label

- hosts: node
  roles:
    - role: wod.k8s-ssl-kubelet
    - role: wod.envoy
    - role: wod.docker-login
    - role: wod.k8s-kubelet
    - role: wod.k8s-cni
    - role: wod.nerdctl

- hosts: master
  roles:
    - role: wod.k8s-helm
      when:
        - "inventory_hostname == groups['master'][0]"
    - role: wod.flannel
      when:
        - "inventory_hostname == groups['master'][0]"
        - "K8S_NETWORK_PLUGIN == 'flannel'"
    - role: wod.cilium
      when:
        - "inventory_hostname == groups['master'][0]"
        - "K8S_NETWORK_PLUGIN == 'cilium'"
    - role: wod.k8s-addon
      when:
        - "inventory_hostname == groups['master'][0]"
