- hosts: all
  gather_facts: False
  roles:
  - wod.python
      
- hosts: master
  vars:
    REGISTRY_LOCAL: registry.cn-qingdao.aliyuncs.com/wod
  roles:
    - role: wod.k8s-helm
      when:
        - "inventory_hostname == groups['master'][0]"