k8sServiceHost: "{{ K8S_MASTER_HOST }}"
k8sServicePort: "{{ K8S_MASTER_PORT }}"

image:
  repository: "{{ REGISTRY_LOCAL }}/{{ K8S_IMAGES["CILIUM"]["NAME"] }}"
  tag: "{{ K8S_IMAGES["CILIUM"]["VERSION"] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}"
  useDigest: false

disableEnvoyVersionCheck: true

{% if REGISTRY_LOCAL == 'registry.beagle.default:6444/k8s' %}
imagePullSecrets:
  - name: beagle-registry
{% endif %}

hubble:
  relay:
    enabled: true
    image:
      repository: "{{ REGISTRY_LOCAL }}/{{ K8S_IMAGES["CILIUM-HUBBLE-RELAY"]["NAME"] }}"
      tag: "{{ K8S_IMAGES["CILIUM-HUBBLE-RELAY"]["VERSION"] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}"
      useDigest: false
  ui:
    enabled: false

operator:
  replicas: 1
  image:
    repository: "{{ REGISTRY_LOCAL }}/{{ "%s" | format(K8S_IMAGES["CILIUM-OPERATOR"]["NAME"]) | replace("-generic", "") }}"
    tag: "{{ K8S_IMAGES["CILIUM-OPERATOR"]["VERSION"] }}{{ "-%s" | format(K8S_ARCH) | replace("-amd64", "") }}"
    useDigest: false

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["{{ K8S_POD_NETWORK }}"]
    clusterPoolIPv4MaskSize: {{ K8S_NODE_PODCIDRMASK }}

kubeProxyReplacement: "false"

nodePort:
  enabled: true
  range: "20,65000"

hostServices:
  enabled: true

externalIPs:
  enabled: true

hostPort:
  enabled: true

endpointStatus:
  enabled: true
  status: "policy"
